apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-local-db.yml
    kompose.version: 1.22.0 (955b78124)
  labels:
    io.kompose.service: mysql-server
  name: mysql-server
spec:
  type: ExternalName
  externalName: james-petclinic.cbanmzptkrzf.us-east-1.rds.amazonaws.com

# apiVersion: v1
# kind: Service
# metadata:
#   annotations:
#     kompose.cmd: kompose convert -f docker-compose-local-db.yml
#     kompose.version: 1.22.0 (955b78124)
#   labels:
#     io.kompose.service: mysql-server
#   name: mysql-server
# spec:
#   type: NodePort
#   ports:
#     - port: 3306
#       targetPort: 3306
#   selector:
#     io.kompose.service: mysql-server
# status:
#   loadBalancer: {}
